run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - unused
    - gofmt
    - goimports
    - revive
    - gosimple
    - staticcheck
    - gosec

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false

  revive:
    min-confidence: 0.8

  goimports:
    local-prefixes: exile

  gosec:
    severity: medium

issues:
  exclude-use-default: false
  exclude-dirs:
    - vendor
    - node_modules
