run:
  timeout: 5m
  go: '1.21'

linters:
  enable:
    # Error checking
    - errcheck
    - govet
    
    # Unused code detection
    - unused
    - ineffassign
    - deadcode
    - structcheck
    - varcheck
    
    # Style and formatting
    - gofmt
    - goimports
    - golint
    
    # Best practices
    - gocritic
    - gosimple
    - staticcheck
    
    # Performance
    - prealloc
    
    # Security
    - gosec
    
    # Documentation
    - godoc

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false

  govet:
    check-shadowing: true
    enable-all: true

  golint:
    min-confidence: 0.8

  goimports:
    local-prefixes: github.com/your-org

  gosec:
    severity: medium
    confidence: high

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - hugeParam

issues:
  exclude-use-default: false
  exclude:
    # Allow underscores in variable names
    - "var-naming:"
  exclude-dirs:
    - vendor
    - node_modules
  exclude-patterns:
    - "_test.go$"
